// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "t_order"

// Order mapped from table <t_order>
type Order struct {
	ID                int64     `gorm:"column:id;type:int(8);primaryKey" json:"id"`
	OrderID           string    `gorm:"column:order_id;type:varchar(64);not null" json:"order_id"`
	SuplierOrderID    string    `gorm:"column:suplier_order_id;type:varchar(255)" json:"suplier_order_id"`
	DeparturePortName string    `gorm:"column:departure_port_name;type:varchar(32);not null" json:"departure_port_name"`
	ArrivalPortName   string    `gorm:"column:arrival_port_name;type:varchar(32);not null" json:"arrival_port_name"`
	DepartureTime     time.Time `gorm:"column:departure_time;type:datetime" json:"departure_time"`
	PassengerNum      int       `gorm:"column:passenger_num;type:int(8)" json:"passenger_num"`
	VehicleNum        int       `gorm:"column:vehicle_num;type:int(8)" json:"vehicle_num"`
	CreateTime        time.Time `gorm:"column:create_time;type:datetime;not null;default:2023-01-01 00:00:00" json:"create_time"`
	UpdateTime        time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
