// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePort = "t_port"

// Port mapped from table <t_port>
type Port struct {
	ID         int64     `gorm:"column:id;type:int(8);primaryKey;autoIncrement:true;comment:自增ID主键" json:"id"`               // 自增ID主键
	Code       string    `gorm:"column:code;type:varchar(32);not null;uniqueIndex:code,priority:1;comment:港口编码" json:"code"` // 港口编码
	Name       string    `gorm:"column:name;type:varchar(32);not null;comment:港口名称" json:"name"`                             // 港口名称
	CityName   string    `gorm:"column:city_name;type:varchar(32);not null;comment:城市名" json:"city_name"`                    // 城市名
	Status     int32     `gorm:"column:status;type:tinyint(4);not null" json:"status"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:2023-07-24 00:00:00" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;default:2023-07-24 00:00:00" json:"update_time"`
}

// TableName Port's table name
func (*Port) TableName() string {
	return TableNamePort
}
